/* WebDev roadmap — course order. Blurb = lecture count + video time.
 * Topic TITLES are stored on sessions, so don't rename casually.
 * Generated from syllabus txt. Do not hand-edit. */

export type JourneyStatus = "todo" | "doing" | "done";
export type WebdevStatus = JourneyStatus;

export interface JourneyTopicMeta { key: string; title: string; blurb: string }

export const WEBDEV_TOPICS: JourneyTopicMeta[] = [
  { key: "introduction", title: "Introduction", blurb: "4 lectures · 32m of videos" },
  { key: "prerequisites", title: "Prerequisites", blurb: "1 lectures · 6m of videos" },
  { key: "live-sessions", title: "Live Sessions", blurb: "7 lectures · 16h 54m of videos" },
  { key: "html-level-1-part-a", title: "HTML (Level 1) - Part A", blurb: "7 lectures · 44m of videos" },
  { key: "html-level-1-part-b", title: "HTML (Level 1) - Part B", blurb: "9 lectures · 58m of videos" },
  { key: "html-level-2", title: "HTML (Level 2)", blurb: "13 lectures · 1h 20m of videos" },
  { key: "html-level-3", title: "HTML (Level 3)", blurb: "16 lectures · 1h 52m of videos" },
  { key: "css-getting-started", title: "CSS - Getting Started", blurb: "15 lectures · 1h 49m of videos" },
  { key: "css-part-2", title: "CSS - Part 2", blurb: "17 lectures · 1h 47m of videos" },
  { key: "css-part-3", title: "CSS - Part 3", blurb: "11 lectures · 1h 27m of videos" },
  { key: "css-part-4", title: "CSS - Part 4", blurb: "11 lectures · 1h 13m of videos" },
  { key: "css-part-5", title: "CSS - Part 5", blurb: "10 lectures · 58m of videos" },
  { key: "css-part-6", title: "CSS - Part 6", blurb: "15 lectures · 1h 27m of videos" },
  { key: "mini-project-css", title: "Mini Project (CSS)", blurb: "9 lectures · 1h 9m of videos" },
  { key: "bootstrap", title: "Bootstrap", blurb: "15 lectures · 1h 40m of videos" },
  { key: "project-css", title: "Project (CSS)", blurb: "13 lectures · 1h 58m of videos" },
  { key: "javascript-part-1", title: "JavaScript (Part 1)", blurb: "21 lectures · 2h 2m of videos" },
  { key: "javascript-part-2", title: "JavaScript (Part 2)", blurb: "19 lectures · 2h 9m of videos" },
  { key: "javascript-part-3", title: "JavaScript (Part 3)", blurb: "25 lectures · 2h 3m of videos" },
  { key: "javascript-part-4", title: "JavaScript (Part 4)", blurb: "15 lectures · 1h 41m of videos" },
  { key: "javascript-part-5", title: "JavaScript (Part 5)", blurb: "12 lectures · 1h 8m of videos" },
  { key: "javascript-part-6", title: "JavaScript (Part 6)", blurb: "17 lectures · 1h 29m of videos" },
  { key: "javascript-part-7", title: "JavaScript (Part 7)", blurb: "8 lectures · 55m of videos" },
  { key: "javascript-part-8", title: "JavaScript (Part 8)", blurb: "13 lectures · 1h 12m of videos" },
  { key: "javascript-part-9", title: "JavaScript (Part 9)", blurb: "15 lectures · 1h 41m of videos" },
  { key: "javascript-part-10", title: "JavaScript (Part 10)", blurb: "10 lectures · 1h 18m of videos" },
  { key: "javascript-mini-project", title: "JavaScript (Mini-Project)", blurb: "11 lectures · 1h 14m of videos" },
  { key: "javascript-part-11", title: "JavaScript (Part 11)", blurb: "11 lectures · 1h 30m of videos" },
  { key: "javascript-part-12", title: "JavaScript (Part 12)", blurb: "15 lectures · 1h 28m of videos" },
  { key: "javascript-part-13", title: "JavaScript (Part 13)", blurb: "4 lectures · 30m of videos" },
  { key: "terminal", title: "Terminal", blurb: "10 lectures · 50m of videos" },
  { key: "git-github", title: "Git & Github", blurb: "20 lectures · 1h 47m of videos" },
  { key: "backend-1-node-js", title: "Backend 1 (Node.js)", blurb: "12 lectures · 1h 8m of videos" },
  { key: "backend-2-node-express", title: "Backend 2 (Node : Express)", blurb: "8 lectures · 50m of videos" },
  { key: "backend-3-node-ejs", title: "Backend 3 (Node : EJS)", blurb: "11 lectures · 1h 11m of videos" },
  { key: "miscellaneous", title: "Miscellaneous", blurb: "8 lectures · 1h 13m of videos" },
  { key: "backend-4-rest", title: "Backend 4 (REST)", blurb: "11 lectures · 1h 28m of videos" },
  { key: "starting-with-sql", title: "Starting with SQL", blurb: "15 lectures · 1h 22m of videos" },
  { key: "sql-part-2", title: "SQL (Part 2)", blurb: "15 lectures · 1h 2m of videos" },
  { key: "backend-5-node-with-sql", title: "Backend 5 (Node with SQL)", blurb: "12 lectures · 1h 31m of videos" },
  { key: "mongodb-part-1", title: "MongoDB (Part 1)", blurb: "10 lectures · 52m of videos" },
  { key: "mongodb-part-2", title: "MongoDB (Part 2)", blurb: "13 lectures · 1h 25m of videos" },
  { key: "mongodb-with-express", title: "MongoDB with Express", blurb: "10 lectures · 1h 13m of videos" },
  { key: "project-phase-1-part-a", title: "Project - Phase 1 (Part a)", blurb: "8 lectures · 1h 6m of videos" },
  { key: "project-phase-1-part-b", title: "Project - Phase 1 (Part b)", blurb: "7 lectures · 1h 10m of videos" },
  { key: "backend-6-middlewares", title: "Backend 6 (Middlewares)", blurb: "8 lectures · 50m of videos" },
  { key: "backend-7-errors", title: "Backend 7 (Errors)", blurb: "8 lectures · 55m of videos" },
  { key: "project-phase-1-part-c", title: "Project - Phase 1 (Part c)", blurb: "8 lectures · 1h 0m of videos" },
  { key: "database-relationships", title: "Database Relationships", blurb: "9 lectures · 1h 14m of videos" },
  { key: "project-phase-2-part-a", title: "Project - Phase 2 (Part a)", blurb: "10 lectures · 1h 20m of videos" },
  { key: "project-phase-2-part-b", title: "Project - Phase 2 (Part b)", blurb: "8 lectures · 57m of videos" },
  { key: "project-phase-2-part-c", title: "Project - Phase 2 (Part c)", blurb: "11 lectures · 1h 14m of videos" },
  { key: "project-phase-2-part-d", title: "Project - Phase 2 (Part d)", blurb: "11 lectures · 1h 14m of videos" },
  { key: "project-phase-2-part-e", title: "Project - Phase 2 (Part e)", blurb: "10 lectures · 1h 19m of videos" },
  { key: "project-phase-3-part-a", title: "Project - Phase 3 (Part a)", blurb: "11 lectures · 1h 29m of videos" },
  { key: "project-phase-3-part-b", title: "Project - Phase 3 (Part b)", blurb: "8 lectures · 1h 23m of videos" },
  { key: "project-phase-3-part-c", title: "Project - Phase 3 (Part c)", blurb: "5 lectures · 40m of videos" },
  { key: "project-phase-3-part-d", title: "Project - Phase 3 (Part d)", blurb: "6 lectures · 51m of videos" },
  { key: "react-part-1", title: "React (Part 1)", blurb: "12 lectures · 1h 10m of videos" },
  { key: "react-part-2", title: "React (Part 2)", blurb: "8 lectures · 1h 5m of videos" },
  { key: "react-part-3", title: "React (Part 3)", blurb: "11 lectures · 1h 10m of videos" },
  { key: "react-part-4", title: "React (Part 4)", blurb: "8 lectures · 1h 2m of videos" },
  { key: "react-part-5", title: "React (Part 5)", blurb: "8 lectures · 1h 6m of videos" },
  { key: "react-part-6", title: "React (Part 6)", blurb: "9 lectures · 1h 34m of videos" },
  { key: "react-major-project", title: "React (Major-Project)", blurb: "6 lectures · 1h 13m of videos" },
  { key: "tailwind", title: "Tailwind", blurb: "7 lectures · 1h 21m of videos" },
  { key: "supplement-redux-redux-toolkit", title: "Supplement : Redux & Redux Toolkit", blurb: "9 lectures · 1h 17m of videos" },
];

export const WEBDEV_KEY_SET = new Set(WEBDEV_TOPICS.map((t) => t.key));
