/* Lecture list per module — generated. Do not hand-edit. */
export interface JourneyLecture { title: string; secs: number }
export const WEBDEV_LECTURES: Record<string, JourneyLecture[]> = {
  "introduction": [
    { title: "Welcome to Delta!", secs: 564 },
    { title: "What is the Internet?", secs: 669 },
    { title: "What is Web Development?", secs: 577 },
    { title: "What will we learn?", secs: 112 },
  ],
  "prerequisites": [
    { title: "Prerequisites", secs: 362 },
  ],
  "live-sessions": [
    { title: "Orientation Session (Recording)", secs: 6720 },
    { title: "Extra Live Session 1 (Recording)", secs: 7740 },
    { title: "Extra Live Session 2 (Recording)", secs: 4500 },
    { title: "Linkedin Mentorship Session by Aman sir", secs: 11640 },
    { title: "Placement & Internships Season 2025-26", secs: 10740 },
    { title: "GSoC Mentorship Session", secs: 10380 },
    { title: "Resume Building Mentorship Session", secs: 9120 },
  ],
  "html-level-1-part-a": [
    { title: "Introduction to HTML", secs: 282 },
    { title: "HTML Elements & Tags", secs: 269 },
    { title: "Hello World", secs: 466 },
    { title: "Paragraph Element", secs: 262 },
    { title: "Heading Elements", secs: 278 },
    { title: "Practice Qs", secs: 403 },
    { title: "Boilerplate Code", secs: 721 },
  ],
  "html-level-1-part-b": [
    { title: "Lists in HTML", secs: 348 },
    { title: "Attributes in HTML", secs: 154 },
    { title: "Anchor Element", secs: 444 },
    { title: "Image Element", secs: 674 },
    { title: "Practice Qs", secs: 244 },
    { title: "More HTML Tags", secs: 260 },
    { title: "Comments in HTML", secs: 491 },
    { title: "Is HTML Case Sensitive?", secs: 182 },
    { title: "Practice Qs", secs: 693 },
  ],
  "html-level-2": [
    { title: "Inline v/s Block", secs: 625 },
    { title: "Div Element", secs: 296 },
    { title: "Span Element", secs: 159 },
    { title: "Hr Tag", secs: 188 },
    { title: "Sup & Sub Tags", secs: 272 },
    { title: "Practice Qs", secs: 112 },
    { title: "Semantic Markup", secs: 412 },
    { title: "Semantic Tags", secs: 617 },
    { title: "Practice Qs", secs: 247 },
    { title: "HTML Entities", secs: 665 },
    { title: "Practice Qs", secs: 172 },
    { title: "Emmets", secs: 719 },
    { title: "Further Understanding HTML", secs: 321 },
  ],
  "html-level-3": [
    { title: "Tables in HTML", secs: 852 },
    { title: "Semantics in Tables", secs: 182 },
    { title: "Colspan & Rowspan Attributes", secs: 585 },
    { title: "Practice Qs", secs: 474 },
    { title: "Forms in HTML", secs: 312 },
    { title: "Input - Form Element", secs: 480 },
    { title: "Placeholders & Labels", secs: 571 },
    { title: "Button Element", secs: 585 },
    { title: "Name Attribute", secs: 624 },
    { title: "Practice Qs", secs: 169 },
    { title: "Checkbox - Input Element", secs: 247 },
    { title: "Radio - Input Element", secs: 527 },
    { title: "Select - Input Element", secs: 253 },
    { title: "Range - Input Element", secs: 304 },
    { title: "Text Area", secs: 197 },
    { title: "Practice Qs", secs: 406 },
  ],
  "css-getting-started": [
    { title: "What is CSS?", secs: 431 },
    { title: "Basic CSS Format", secs: 262 },
    { title: "Including CSS", secs: 891 },
    { title: "Color Property", secs: 343 },
    { title: "Background Color Property", secs: 154 },
    { title: "Practice Qs", secs: 183 },
    { title: "Color Systems (Name & RGB)", secs: 770 },
    { title: "Hex Codes", secs: 681 },
    { title: "Practice Qs", secs: 114 },
    { title: "Text Align Property", secs: 602 },
    { title: "Font Weight & Text Decoration", secs: 632 },
    { title: "Line Height & Letter Spacing", secs: 276 },
    { title: "Units in CSS (Pixel)", secs: 420 },
    { title: "Font Family", secs: 421 },
    { title: "Practice Qs", secs: 404 },
  ],
  "css-part-2": [
    { title: "How to download?", secs: 40 },
    { title: "Universal Selector", secs: 395 },
    { title: "Element Selector", secs: 157 },
    { title: "Id Selector", secs: 250 },
    { title: "Class Selector", secs: 270 },
    { title: "Practice Qs", secs: 325 },
    { title: "Descendant Selector", secs: 484 },
    { title: "Sibling Combinator", secs: 291 },
    { title: "Child Combinator", secs: 239 },
    { title: "Attribute Selector", secs: 291 },
    { title: "Practice Qs", secs: 206 },
    { title: "Pseudo Class", secs: 981 },
    { title: "Pseudo Element", secs: 291 },
    { title: "Cascading & Specificity", secs: 882 },
    { title: "Practice Qs", secs: 377 },
    { title: "!important in CSS", secs: 99 },
    { title: "Inheritance", secs: 901 },
  ],
  "css-part-3": [
    { title: "Box Model", secs: 268 },
    { title: "Height & Width", secs: 454 },
    { title: "Border", secs: 549 },
    { title: "Border Radius", secs: 337 },
    { title: "Padding Property", secs: 707 },
    { title: "Margin Property", secs: 384 },
    { title: "Practice Qs", secs: 421 },
    { title: "Display Property", secs: 721 },
    { title: "Inline-Block", secs: 245 },
    { title: "Relative Units (Percentage)", secs: 427 },
    { title: "Em & Rem in Units", secs: 766 },
  ],
  "css-part-4": [
    { title: "Alpha & Opacity", secs: 459 },
    { title: "Transitions in CSS", secs: 605 },
    { title: "Transform - Rotate", secs: 302 },
    { title: "Tranform - Scale", secs: 192 },
    { title: "Transform - Translate", secs: 113 },
    { title: "Transform - Skew", secs: 169 },
    { title: "Box Shadow", secs: 201 },
    { title: "Background Image", secs: 271 },
    { title: "Card Hover Effect", secs: 502 },
    { title: "Position Property", secs: 855 },
    { title: "Simple Smiley Face", secs: 766 },
  ],
  "css-part-5": [
    { title: "What is Flexbox?", secs: 403 },
    { title: "Display Flex", secs: 490 },
    { title: "Flex Direction", secs: 279 },
    { title: "Justify Content", secs: 484 },
    { title: "Flex Wrap", secs: 303 },
    { title: "Align Items", secs: 323 },
    { title: "Align Content", secs: 200 },
    { title: "Align Self", secs: 146 },
    { title: "Flex Sizing", secs: 669 },
    { title: "Flex Shorthand", secs: 194 },
  ],
  "css-part-6": [
    { title: "What is Grid?", secs: 380 },
    { title: "Grid Model", secs: 215 },
    { title: "Grid Template", secs: 529 },
    { title: "Grid Template (repeat)", secs: 291 },
    { title: "Grid Gaps", secs: 190 },
    { title: "Grid Columns", secs: 290 },
    { title: "Grid Rows", secs: 150 },
    { title: "Grid Properties", secs: 323 },
    { title: "Animation in CSS", secs: 672 },
    { title: "Animation Shorthand", secs: 150 },
    { title: "% in Animation", secs: 108 },
    { title: "Media Queries", secs: 792 },
    { title: "Media Queries (Orientation)", secs: 91 },
    { title: "Pet Adoption Page", secs: 501 },
    { title: "z-index", secs: 572 },
  ],
  "mini-project-css": [
    { title: "Color Theory", secs: 741 },
    { title: "Typography", secs: 212 },
    { title: "Google Fonts", secs: 398 },
    { title: "Icons", secs: 336 },
    { title: "Introduction", secs: 443 },
    { title: "Setting Style", secs: 409 },
    { title: "Sidebar Menu", secs: 908 },
    { title: "Hover Changes", secs: 244 },
    { title: "Configuring Checkbox", secs: 460 },
  ],
  "bootstrap": [
    { title: "What is Bootstrap?", secs: 740 },
    { title: "Using Bootstrap", secs: 547 },
    { title: "Container (Layout)", secs: 373 },
    { title: "Button (Component)", secs: 401 },
    { title: "Badge (Component)", secs: 331 },
    { title: "Alert (Component)", secs: 385 },
    { title: "Button Group (Component)", secs: 198 },
    { title: "Navbar (Component)", secs: 971 },
    { title: "Card (Component)", secs: 235 },
    { title: "Grid (Layout)", secs: 769 },
    { title: "Grid (Vertical Alignment)", secs: 170 },
    { title: "Form Controls in Bootstrap", secs: 382 },
    { title: "Select in Form", secs: 150 },
    { title: "Checkbox & Radio in Form", secs: 229 },
    { title: "Form Layout", secs: 143 },
  ],
  "project-css": [
    { title: "Setting up", secs: 467 },
    { title: "Basics", secs: 679 },
    { title: "Layout", secs: 568 },
    { title: "Sidebar (Nav)", secs: 631 },
    { title: "Sidebar (Library)", secs: 592 },
    { title: "Library Boxes", secs: 773 },
    { title: "Sticky Nav", secs: 883 },
    { title: "Cards", secs: 815 },
    { title: "Footer Line", secs: 233 },
    { title: "Setting up Player", secs: 428 },
    { title: "Player Controls", secs: 321 },
    { title: "Playback Bar", secs: 693 },
    { title: "Tailwind CSS", secs: 45 },
  ],
  "javascript-part-1": [
    { title: "Introduction", secs: 266 },
    { title: "Using the Console", secs: 459 },
    { title: "What is a Variable?", secs: 458 },
    { title: "Data Types in JS", secs: 357 },
    { title: "Numbers in JS", secs: 434 },
    { title: "Operations in JS", secs: 443 },
    { title: "NaN in JS", secs: 153 },
    { title: "Operator Precedence", secs: 379 },
    { title: "let, const & var Keywords", secs: 842 },
    { title: "Practice Qs", secs: 311 },
    { title: "Assignment Operators", secs: 163 },
    { title: "Unary Operators", secs: 448 },
    { title: "Practice Qs", secs: 135 },
    { title: "Identifier Rules", secs: 459 },
    { title: "Boolean in JS", secs: 221 },
    { title: "What is TypeScript?", secs: 136 },
    { title: "Practice Qs", secs: 103 },
    { title: "String in JS", secs: 422 },
    { title: "String Indices", secs: 572 },
    { title: "null & undefined in JS", secs: 274 },
    { title: "Practice Qs", secs: 293 },
  ],
  "javascript-part-2": [
    { title: "console.log( )", secs: 297 },
    { title: "Linking JS File", secs: 483 },
    { title: "Template Literals", secs: 426 },
    { title: "Operators in JS", secs: 370 },
    { title: "Comparison Operators", secs: 606 },
    { title: "Comparison for Non-numbers", secs: 271 },
    { title: "Conditional Statements", secs: 190 },
    { title: "if Statement", secs: 489 },
    { title: "Practice Qs", secs: 320 },
    { title: "else if Statement", secs: 520 },
    { title: "else Statement", secs: 226 },
    { title: "Practice Qs", secs: 236 },
    { title: "Nested if-else", secs: 169 },
    { title: "Logical Operators", secs: 692 },
    { title: "Practice Qs", secs: 734 },
    { title: "truthy & falsy", secs: 449 },
    { title: "Switch Statement", secs: 485 },
    { title: "Practice Qs", secs: 265 },
    { title: "Alerts & Prompts", secs: 548 },
  ],
  "javascript-part-3": [
    { title: "String Methods", secs: 158 },
    { title: "Trim Method", secs: 317 },
    { title: "Strings are Immutable in JS", secs: 81 },
    { title: "ToUpperCase and ToLowerCase", secs: 119 },
    { title: "Methods with Arguments - indexOf", secs: 290 },
    { title: "Method Chaining", secs: 168 },
    { title: "Slice Method", secs: 398 },
    { title: "Replace & Repeat Method", secs: 244 },
    { title: "Practice Qs", secs: 480 },
    { title: "Array (Data Structure)", secs: 370 },
    { title: "Visualizing Arrays", secs: 245 },
    { title: "Creating Arrays", secs: 263 },
    { title: "Arrays are Mutable", secs: 250 },
    { title: "Array Methods", secs: 422 },
    { title: "Practice Qs", secs: 191 },
    { title: "indexOf & includes Method", secs: 227 },
    { title: "Concatenation & Reverse", secs: 258 },
    { title: "Slice in Arrays", secs: 324 },
    { title: "Splice in Arrays", secs: 548 },
    { title: "Sort in Arrays", secs: 196 },
    { title: "Practice Qs", secs: 264 },
    { title: "Arrays References", secs: 594 },
    { title: "Constant Arrays", secs: 288 },
    { title: "Nested Arrays", secs: 401 },
    { title: "Practice Qs", secs: 292 },
  ],
  "javascript-part-4": [
    { title: "for Loops", secs: 476 },
    { title: "Dry Run", secs: 560 },
    { title: "Print Odd Numbers", secs: 328 },
    { title: "Print Even Numbers", secs: 226 },
    { title: "Infinite Loops", secs: 239 },
    { title: "Print Multiplication Table", secs: 326 },
    { title: "Nested for Loop", secs: 538 },
    { title: "while Loops", secs: 299 },
    { title: "Favorite Movie", secs: 652 },
    { title: "break Keyword", secs: 252 },
    { title: "Loops with Arrays", secs: 420 },
    { title: "Loops with Nested Arrays", secs: 512 },
    { title: "for-of Loops", secs: 254 },
    { title: "Nested for-of Loop", secs: 98 },
    { title: "Todo App (only JS)", secs: 882 },
  ],
  "javascript-part-5": [
    { title: "Object Literals", secs: 239 },
    { title: "Creating Object Literals", secs: 463 },
    { title: "Creating a Post", secs: 178 },
    { title: "Get Values", secs: 266 },
    { title: "Conversion in Get Values", secs: 265 },
    { title: "Add / Update Values", secs: 320 },
    { title: "Nested Objects", secs: 228 },
    { title: "Array of Objects", secs: 225 },
    { title: "Math Object", secs: 485 },
    { title: "Random Integers", secs: 384 },
    { title: "Practice Qs", secs: 179 },
    { title: "Guessing Game", secs: 876 },
  ],
  "javascript-part-6": [
    { title: "What are functions?", secs: 536 },
    { title: "Practice Qs1", secs: 71 },
    { title: "Practice Qs 2", secs: 207 },
    { title: "Functions with Arguments", secs: 478 },
    { title: "Practice Qs 3", secs: 206 },
    { title: "Practice Qs 4", secs: 154 },
    { title: "return Keyword", secs: 604 },
    { title: "Practice Qs 5", secs: 226 },
    { title: "Practice Qs 6", secs: 261 },
    { title: "What is Scope?", secs: 349 },
    { title: "Block Scope", secs: 249 },
    { title: "Lexical Scope", secs: 297 },
    { title: "Practice Qs 7", secs: 291 },
    { title: "Functions Expressions", secs: 235 },
    { title: "Higher Order Functions", secs: 348 },
    { title: "Higher Order Functions (Returns)", secs: 413 },
    { title: "Methods", secs: 422 },
  ],
  "javascript-part-7": [
    { title: "'this' in JavaScript", secs: 491 },
    { title: "Try & Catch", secs: 385 },
    { title: "Arrow Functions", secs: 518 },
    { title: "Implicit Return in Arrow Functions", secs: 272 },
    { title: "Set TimeOut Function", secs: 318 },
    { title: "Set Interval Function", secs: 236 },
    { title: "this with Arrow Functions", secs: 805 },
    { title: "Practice Qs", secs: 329 },
  ],
  "javascript-part-8": [
    { title: "Array Methods", secs: 285 },
    { title: "Map & Filter", secs: 477 },
    { title: "Every & Sum", secs: 159 },
    { title: "Reduce Method", secs: 604 },
    { title: "Maximum in Array", secs: 287 },
    { title: "Practice Qs", secs: 260 },
    { title: "Default Parameters", secs: 265 },
    { title: "Spread", secs: 295 },
    { title: "Spread (Array Literals)", secs: 210 },
    { title: "Spread (Object Literals)", secs: 269 },
    { title: "Rest", secs: 631 },
    { title: "Destructuring", secs: 237 },
    { title: "Destructuring (Objects)", secs: 354 },
  ],
  "javascript-part-9": [
    { title: "Introduction", secs: 102 },
    { title: "What is DOM?", secs: 292 },
    { title: "Download Starter Code", secs: 568 },
    { title: "Selecting Element by ID", secs: 378 },
    { title: "Selecting Elements by Class Name", secs: 326 },
    { title: "Selecting Elements by Tag Name", secs: 130 },
    { title: "Query Selectors", secs: 379 },
    { title: "Setting Content in Objects", secs: 647 },
    { title: "Manipulating Attributes", secs: 280 },
    { title: "Manipulating Style (with style attribute)", secs: 518 },
    { title: "classList Property", secs: 726 },
    { title: "Navigation on Page", secs: 506 },
    { title: "Adding Elements on Page", secs: 740 },
    { title: "Removing Elements from Page", secs: 107 },
    { title: "Practice Qs", secs: 409 },
  ],
  "javascript-part-10": [
    { title: "DOM Events", secs: 309 },
    { title: "Mouse/ Pointer Events", secs: 536 },
    { title: "Event Listeners", secs: 412 },
    { title: "Activity", secs: 618 },
    { title: "Event Listeners for Elements", secs: 163 },
    { title: "this in Event Listeners", secs: 469 },
    { title: "Keyboard Events", secs: 901 },
    { title: "Form Events", secs: 250 },
    { title: "Extracting Form Data", secs: 575 },
    { title: "More Events", secs: 475 },
  ],
  "javascript-mini-project": [
    { title: "Event Bubbling", secs: 214 },
    { title: "Building Todo with DOM", secs: 688 },
    { title: "Event Delegation", secs: 521 },
    { title: "What is Simon Say Game?", secs: 0 },
    { title: "Setting up Project", secs: 551 },
    { title: "Start Game", secs: 493 },
    { title: "Flash Buttons & Level Up", secs: 521 },
    { title: "Button Event Listeners", secs: 309 },
    { title: "Matching Sequence", secs: 806 },
    { title: "Reset Game", secs: 147 },
    { title: "Display Score", secs: 242 },
  ],
  "javascript-part-11": [
    { title: "JS Call Stack", secs: 659 },
    { title: "Visualizing the Call stack", secs: 414 },
    { title: "Breakpoints", secs: 446 },
    { title: "JS is Single Threaded", secs: 649 },
    { title: "Callback Hell", secs: 699 },
    { title: "Setting up for Promises", secs: 680 },
    { title: "Refactoring with Promises", secs: 474 },
    { title: "then( ) and catch( ) methods", secs: 291 },
    { title: "Promise chaining", secs: 450 },
    { title: "Results & Errors in Promises", secs: 206 },
    { title: "Refactoring old code", secs: 456 },
  ],
  "javascript-part-12": [
    { title: "async Functions", secs: 452 },
    { title: "await Keyword", secs: 476 },
    { title: "Handing Rejections", secs: 272 },
    { title: "What is an API?", secs: 389 },
    { title: "Accessing some APIs", secs: 471 },
    { title: "What is JSON?", secs: 294 },
    { title: "Accessing JSON data", secs: 282 },
    { title: "API Testing Tools", secs: 269 },
    { title: "What is Ajax?", secs: 195 },
    { title: "Https Verbs", secs: 100 },
    { title: "Status Codes", secs: 179 },
    { title: "Adding Information in URLs", secs: 685 },
    { title: "Https Headers", secs: 407 },
    { title: "Our First API request", secs: 639 },
    { title: "Using Fetch with async-await", secs: 206 },
  ],
  "javascript-part-13": [
    { title: "Using Axios", secs: 566 },
    { title: "DogPictures API", secs: 321 },
    { title: "Sending Headers with API requests", secs: 165 },
    { title: "Activity using Query Strings", secs: 779 },
  ],
  "terminal": [
    { title: "What is the Terminal?", secs: 297 },
    { title: "Different Terms related to Terminal", secs: 348 },
    { title: "(Window Users Only) Installing Git Bash", secs: 166 },
    { title: "Basic Commands", secs: 332 },
    { title: "Navigation Commands", secs: 357 },
    { title: "Paths in Navigation", secs: 290 },
    { title: "Making Directories", secs: 275 },
    { title: "What are Flags?", secs: 410 },
    { title: "Touch Command", secs: 157 },
    { title: "Deleting Files & Folders", secs: 375 },
  ],
  "git-github": [
    { title: "What is Git & Github?", secs: 515 },
    { title: "Creating a Github Account", secs: 153 },
    { title: "Using Github", secs: 851 },
    { title: "Using Git", secs: 171 },
    { title: "Configuring Git", secs: 133 },
    { title: "Git with VSCode", secs: 130 },
    { title: "Clone command", secs: 359 },
    { title: "Status command", secs: 287 },
    { title: "Add & Commit Commands", secs: 363 },
    { title: "Push command", secs: 268 },
    { title: "Init Command", secs: 137 },
    { title: "Pushing Local repo", secs: 652 },
    { title: "Workflow", secs: 86 },
    { title: "Git branches", secs: 382 },
    { title: "Branch Commands", secs: 178 },
    { title: "Merging Branches", secs: 596 },
    { title: "Pull command", secs: 122 },
    { title: "Merge Conflicts", secs: 352 },
    { title: "Fixing Mistakes", secs: 370 },
    { title: "What is Forking?", secs: 371 },
  ],
  "backend-1-node-js": [
    { title: "What is node.js?", secs: 205 },
    { title: "Node Installation", secs: 110 },
    { title: "Node REPL", secs: 214 },
    { title: "Node Files", secs: 154 },
    { title: "Process in Node", secs: 416 },
    { title: "Export in Files", secs: 592 },
    { title: "Export in Directories", secs: 377 },
    { title: "What is npm?", secs: 240 },
    { title: "Installing Packages", secs: 592 },
    { title: "package.json", secs: 509 },
    { title: "Local v/s Global Installation", secs: 200 },
    { title: "import modules", secs: 495 },
  ],
  "backend-2-node-express": [
    { title: "What is Express?", secs: 259 },
    { title: "Getting started with Express", secs: 636 },
    { title: "Handling requests", secs: 255 },
    { title: "Sending a Response", secs: 405 },
    { title: "Routing", secs: 543 },
    { title: "Installing Nodemon", secs: 163 },
    { title: "Path Parameters", secs: 404 },
    { title: "Query Strings", secs: 342 },
  ],
  "backend-3-node-ejs": [
    { title: "What is Templating?", secs: 397 },
    { title: "Using EJS", secs: 558 },
    { title: "Views Directory", secs: 123 },
    { title: "Interpolation Syntax", secs: 402 },
    { title: "Passing data to EJS", secs: 287 },
    { title: "Instagram EJS", secs: 246 },
    { title: "Conditional Statements", secs: 219 },
    { title: "Loops", secs: 214 },
    { title: "Instagram Page with EJS", secs: 826 },
    { title: "Serving Static Files", secs: 564 },
    { title: "Includes", secs: 440 },
  ],
  "miscellaneous": [
    { title: "GET & POST Request", secs: 797 },
    { title: "Handling POST requests", secs: 370 },
    { title: "Revisiting JS (OOPS)", secs: 489 },
    { title: "Object Prototypes", secs: 804 },
    { title: "Factory Functions", secs: 331 },
    { title: "New Operator", secs: 600 },
    { title: "Classes in JS", secs: 219 },
    { title: "Inheritance", secs: 788 },
  ],
  "backend-4-rest": [
    { title: "What is REST?", secs: 663 },
    { title: "CRUD Operations", secs: 194 },
    { title: "Creating RESTful APIs", secs: 465 },
    { title: "Index Route", secs: 523 },
    { title: "Create & New Route", secs: 576 },
    { title: "Redirect", secs: 297 },
    { title: "Show Route", secs: 629 },
    { title: "Creating Ids (UUID)", secs: 255 },
    { title: "Update Route", secs: 396 },
    { title: "Edit Route", secs: 843 },
    { title: "Destroy Route", secs: 482 },
  ],
  "starting-with-sql": [
    { title: "What is a Database?", secs: 318 },
    { title: "SQL v/s NoSQL", secs: 388 },
    { title: "What is SQL?", secs: 346 },
    { title: "What is a Table?", secs: 232 },
    { title: "(For Windows) Installation", secs: 232 },
    { title: "(For Mac) Installation", secs: 269 },
    { title: "Our First Database", secs: 432 },
    { title: "Our First Table", secs: 280 },
    { title: "Database Queries", secs: 199 },
    { title: "CREATE Table", secs: 538 },
    { title: "What are Constraints?", secs: 340 },
    { title: "Key Constraints", secs: 669 },
    { title: "Primary & Foreign Keys", secs: 197 },
    { title: "INSERT into Table", secs: 337 },
    { title: "SELECT Command", secs: 165 },
  ],
  "sql-part-2": [
    { title: "Where Clause", secs: 160 },
    { title: "Operators in Where", secs: 285 },
    { title: "Frequently Used Operators", secs: 389 },
    { title: "Limit Clause", secs: 98 },
    { title: "Order By Clause", secs: 137 },
    { title: "Aggregate Functions", secs: 230 },
    { title: "Group By Clause", secs: 302 },
    { title: "Having Clause", secs: 153 },
    { title: "General Order", secs: 80 },
    { title: "UPDATE Table", secs: 183 },
    { title: "DELETE Table", secs: 68 },
    { title: "ALTER Table", secs: 430 },
    { title: "TRUNCATE Table", secs: 211 },
    { title: "Practice Qs1", secs: 540 },
    { title: "Practice Qs2", secs: 461 },
  ],
  "backend-5-node-with-sql": [
    { title: "Using Faker", secs: 357 },
    { title: "MySQL Package", secs: 804 },
    { title: "Using SQL from CLI", secs: 189 },
    { title: "CREATE Table user", secs: 358 },
    { title: "INSERT INTO user", secs: 419 },
    { title: "Insert in Bulk", secs: 286 },
    { title: "Routing", secs: 253 },
    { title: "Home Route", secs: 487 },
    { title: "Add Template", secs: 287 },
    { title: "Show Route", secs: 486 },
    { title: "Edit Route", secs: 756 },
    { title: "Update Route", secs: 793 },
  ],
  "mongodb-part-1": [
    { title: "The Mongo Shell", secs: 502 },
    { title: "How we store data? (BSON)", secs: 185 },
    { title: "Document & Collection", secs: 168 },
    { title: "INSERT in DB (InsertOne)", secs: 455 },
    { title: "INSERT in DB (InsertMany)", secs: 107 },
    { title: "FIND in DB", secs: 335 },
    { title: "Query Operators", secs: 523 },
    { title: "UPDATE in DB", secs: 440 },
    { title: "Nesting", secs: 161 },
    { title: "DELETE in DB", secs: 252 },
  ],
  "mongodb-part-2": [
    { title: "What is mongoose?", secs: 163 },
    { title: "Installation & Setup", secs: 626 },
    { title: "Schema", secs: 290 },
    { title: "Models", secs: 373 },
    { title: "Insert in Mongoose", secs: 448 },
    { title: "Insert Multiple", secs: 286 },
    { title: "Find in Mongoose", secs: 479 },
    { title: "Update in Mongoose", secs: 256 },
    { title: "FindAndUpdate", secs: 221 },
    { title: "Delete in Mongoose", secs: 245 },
    { title: "Schema Validations", secs: 867 },
    { title: "SchemaType Options", secs: 535 },
    { title: "Validation in Updation & Errors", secs: 368 },
  ],
  "mongodb-with-express": [
    { title: "Basic Set Up", secs: 353 },
    { title: "Creating our Model (Chat)", secs: 700 },
    { title: "Initialize Database", secs: 259 },
    { title: "Index Route", secs: 714 },
    { title: "New Route", secs: 375 },
    { title: "Create Route", secs: 392 },
    { title: "Using Date", secs: 360 },
    { title: "Edit Route", secs: 421 },
    { title: "Update Route", secs: 488 },
    { title: "Destroy Route", secs: 328 },
  ],
  "project-phase-1-part-a": [
    { title: "Basic Set up", secs: 535 },
    { title: "Listing Model", secs: 949 },
    { title: "Initialize Database", secs: 321 },
    { title: "Index Route", secs: 434 },
    { title: "READ (Show Route)", secs: 344 },
    { title: "CREATE (New & Create Route)", secs: 631 },
    { title: "UPDATE (Edit & Update Route)", secs: 572 },
    { title: "DELETE (Delete Route)", secs: 177 },
  ],
  "project-phase-1-part-b": [
    { title: "Creating Boilerplate", secs: 576 },
    { title: "Navbar", secs: 705 },
    { title: "Footer", secs: 566 },
    { title: "Styling Index", secs: 873 },
    { title: "Styling New Listing", secs: 625 },
    { title: "Styling Edit Listing", secs: 287 },
    { title: "Styling Show Listing", secs: 577 },
  ],
  "backend-6-middlewares": [
    { title: "What are Middlewares?", secs: 464 },
    { title: "Our 1st Middleware", secs: 405 },
    { title: "Using next( )", secs: 492 },
    { title: "Creating Utility Middleware", secs: 487 },
    { title: "Exploring app.use( )", secs: 346 },
    { title: "API Token as Query String", secs: 271 },
    { title: "Passing multiple Middlewares", secs: 77 },
    { title: "Error Handling (Express Default)", secs: 474 },
  ],
  "backend-7-errors": [
    { title: "Error Handling Middleware", secs: 386 },
    { title: "Custom Error Class", secs: 461 },
    { title: "Default Status & Message", secs: 341 },
    { title: "Activity", secs: 114 },
    { title: "Handling Async Errors", secs: 652 },
    { title: "Using try-catch", secs: 465 },
    { title: "Using wrapAsync", secs: 545 },
    { title: "Mongoose Errors", secs: 362 },
  ],
  "project-phase-1-part-c": [
    { title: "Client-Side Validation (Form)", secs: 576 },
    { title: "Success & Failure Text", secs: 562 },
    { title: "Custom Error Handling", secs: 247 },
    { title: "Add wrapAsync", secs: 195 },
    { title: "Add ExpressError", secs: 554 },
    { title: "Error.ejs", secs: 356 },
    { title: "Validation for Schema", secs: 914 },
    { title: "Validation for Schema (Middleware)", secs: 246 },
  ],
  "database-relationships": [
    { title: "SQL Relationships (One to One)", secs: 328 },
    { title: "SQL Relationships (One to Many & Many to Many)", secs: 512 },
    { title: "One to Few (in Detail)", secs: 474 },
    { title: "One to Few (Implementation)", secs: 529 },
    { title: "One to Many (in Detail)", secs: 246 },
    { title: "One to Many (Implementation)", secs: 758 },
    { title: "using Populate", secs: 198 },
    { title: "One to Squillions (in Detail)", secs: 788 },
    { title: "Reading Docs", secs: 608 },
  ],
  "project-phase-2-part-a": [
    { title: "Handling Deletion", secs: 563 },
    { title: "Mongoose Middlewares", secs: 677 },
    { title: "Creating Review Model", secs: 498 },
    { title: "Create Reviews (Step 1)", secs: 403 },
    { title: "Create Reviews (Step 2)", secs: 614 },
    { title: "Validation for Reviews", secs: 595 },
    { title: "Render Reviews", secs: 324 },
    { title: "Styling Reviews", secs: 335 },
    { title: "Deleting Reviews", secs: 521 },
    { title: "Handling : Delete Listing", secs: 321 },
  ],
  "project-phase-2-part-b": [
    { title: "What is Express Router", secs: 539 },
    { title: "Using Express Router", secs: 523 },
    { title: "Restructuring Listings", secs: 397 },
    { title: "Restructuring Reviews", secs: 544 },
    { title: "Web Cookies", secs: 373 },
    { title: "Sending Cookies", secs: 205 },
    { title: "Cookie Parser", secs: 293 },
    { title: "Signed Cookies", secs: 551 },
  ],
  "project-phase-2-part-c": [
    { title: "What is State?", secs: 268 },
    { title: "Express Sessions", secs: 782 },
    { title: "Exploring Session Options", secs: 580 },
    { title: "Storing & Using Session Info", secs: 400 },
    { title: "Using connect-flash", secs: 577 },
    { title: "Using res.locals", secs: 303 },
    { title: "Implement Sessions in Project", secs: 143 },
    { title: "Cookie in SessionOptions", secs: 387 },
    { title: "Implement Flash in Project", secs: 234 },
    { title: "Flash Success Includes", secs: 527 },
    { title: "Flash Failure Includes", secs: 284 },
  ],
  "project-phase-2-part-d": [
    { title: "Authentication v/s Authorization", secs: 205 },
    { title: "How are passwords stored?", secs: 447 },
    { title: "What is Hashing?", secs: 557 },
    { title: "What is Salting?", secs: 355 },
    { title: "Passport - Getting started", secs: 337 },
    { title: "User Model", secs: 322 },
    { title: "Configuring Strategy", secs: 424 },
    { title: "Demo User", secs: 345 },
    { title: "SignUp User - GET", secs: 528 },
    { title: "SignUp User - POST", secs: 455 },
    { title: "Login User", secs: 474 },
  ],
  "project-phase-2-part-e": [
    { title: "Connecting Login Route", secs: 562 },
    { title: "LogOut User", secs: 203 },
    { title: "Add Styling", secs: 346 },
    { title: "Login after SignUp", secs: 291 },
    { title: "post-Login Page", secs: 685 },
    { title: "Listing Owner", secs: 660 },
    { title: "Starting with Authorization", secs: 409 },
    { title: "Authorization for /listings", secs: 672 },
    { title: "Authorization for /reviews (part1)", secs: 405 },
    { title: "Authorization for /reviews (part2)", secs: 558 },
  ],
  "project-phase-3-part-a": [
    { title: "MVC - Model, View, Controller", secs: 413 },
    { title: "MVC for Listings", secs: 232 },
    { title: "MVC for Reviews & Users", secs: 434 },
    { title: "Router.route", secs: 446 },
    { title: "Re-style Ratings", secs: 691 },
    { title: "Image Upload", secs: 536 },
    { title: "Manipulating Form", secs: 638 },
    { title: "Cloud Setup", secs: 612 },
    { title: "Store Files", secs: 628 },
    { title: "Save Link in Mongo", secs: 456 },
    { title: "Display Image", secs: 293 },
  ],
  "project-phase-3-part-b": [
    { title: "Edit Listing Image", secs: 424 },
    { title: "Image Preview for Edit Page", secs: 530 },
    { title: "Getting Started with Maps", secs: 376 },
    { title: "Our First Map", secs: 1085 },
    { title: "Geocoding", secs: 1163 },
    { title: "Storing Coordinates", secs: 495 },
    { title: "Map Marker", secs: 462 },
    { title: "Map Popup", secs: 472 },
  ],
  "project-phase-3-part-c": [
    { title: "Fixing Home Page", secs: 227 },
    { title: "Add UI for Filters", secs: 554 },
    { title: "Add UI for Tax Switch", secs: 502 },
    { title: "Making Tax Switch Functional", secs: 612 },
    { title: "Add UI for Search", secs: 512 },
  ],
  "project-phase-3-part-d": [
    { title: "Using Mongo Atlas", secs: 971 },
    { title: "Mongo Session Store", secs: 680 },
    { title: "Deployment with Render", secs: 236 },
    { title: "Push code to Github", secs: 398 },
    { title: "Connect Render with Github", secs: 253 },
    { title: "Create New Service", secs: 527 },
  ],
  "react-part-1": [
    { title: "What is React?", secs: 784 },
    { title: "What is JSX?", secs: 221 },
    { title: "Set up Local Environment", secs: 404 },
    { title: "Understanding our App", secs: 502 },
    { title: "Re-write App", secs: 195 },
    { title: "Our 1st Component", secs: 526 },
    { title: "Import-Export", secs: 285 },
    { title: "Writing Markup in JSX", secs: 352 },
    { title: "React Fragment", secs: 110 },
    { title: "JSX with Curly Braces", secs: 147 },
    { title: "Structuring Components", secs: 353 },
    { title: "Style Components", secs: 349 },
  ],
  "react-part-2": [
    { title: "React Props", secs: 714 },
    { title: "Passing Arrays to Props", secs: 348 },
    { title: "Rendering Arrays", secs: 257 },
    { title: "Conditionals", secs: 435 },
    { title: "Dynamic Component Styling", secs: 305 },
    { title: "Activity", secs: 247 },
    { title: "Install React Developer Tools", secs: 254 },
    { title: "Activity : Amazon Cards", secs: 1397 },
  ],
  "react-part-3": [
    { title: "Handling Click Events", secs: 272 },
    { title: "Handling Non-Click Events", secs: 278 },
    { title: "Event Object", secs: 387 },
    { title: "State in React", secs: 540 },
    { title: "Hooks", secs: 103 },
    { title: "useState( )", secs: 578 },
    { title: "Activity : Create LikeButton", secs: 717 },
    { title: "Closure in JS", secs: 363 },
    { title: "Re-render : How does it work?", secs: 305 },
    { title: "Callback in Set State Function", secs: 314 },
    { title: "More about State", secs: 377 },
  ],
  "react-part-4": [
    { title: "Objects & State", secs: 890 },
    { title: "Arrays & State", secs: 239 },
    { title: "Activity : Create a Todo", secs: 974 },
    { title: "Unique Key for List Items", secs: 370 },
    { title: "Deleting from Arrays", secs: 534 },
    { title: "Update All in Array", secs: 347 },
    { title: "Update One in Array", secs: 220 },
    { title: "Add a \"Mark as Done\" Feature to Todo", secs: 155 },
  ],
  "react-part-5": [
    { title: "Todo Solution - Mark as Done Feature", secs: 476 },
    { title: "Lottery Game (Part a)", secs: 609 },
    { title: "Lottery Game (Part b)", secs: 384 },
    { title: "Changes to Lottery Game", secs: 769 },
    { title: "Component Types", secs: 324 },
    { title: "Ticket Component", secs: 538 },
    { title: "Lottery Component", secs: 298 },
    { title: "Functions as Props", secs: 589 },
  ],
  "react-part-6": [
    { title: "Forms in React", secs: 851 },
    { title: "Labels in React", secs: 122 },
    { title: "Handling Multiple Inputs", secs: 1039 },
    { title: "Comments Form", secs: 674 },
    { title: "Show Comments", secs: 861 },
    { title: "Validations", secs: 769 },
    { title: "useEffect( )", secs: 431 },
    { title: "Dependencies in useEffect( )", secs: 213 },
    { title: "Use Cases", secs: 739 },
  ],
  "react-major-project": [
    { title: "Material UI", secs: 948 },
    { title: "Building Search Box", secs: 684 },
    { title: "Using Weather API", secs: 888 },
    { title: "Building Info Box", secs: 715 },
    { title: "Weather App Component", secs: 731 },
    { title: "Added Feature", secs: 418 },
  ],
  "tailwind": [
    { title: "Introduction to Tailwind", secs: 719 },
    { title: "Tailwind CLI", secs: 586 },
    { title: "Typography & Styling", secs: 699 },
    { title: "Colors & Spacing", secs: 1272 },
    { title: "Breakpoints in Tailwind", secs: 253 },
    { title: "Apply Directive", secs: 342 },
    { title: "Design a Card in Tailwind", secs: 1041 },
  ],
  "supplement-redux-redux-toolkit": [
    { title: "What is Redux?", secs: 875 },
    { title: "Understanding Terms", secs: 245 },
    { title: "Setup Project", secs: 211 },
    { title: "Configuring Store", secs: 402 },
    { title: "Deciding Actions", secs: 284 },
    { title: "Creating Reducers", secs: 1168 },
    { title: "Todo Component (Provider & useSelector)", secs: 511 },
    { title: "AddTodo (Dispatching Actions)", secs: 515 },
    { title: "Delete Todo", secs: 463 },
  ],
};
